[project]
name = "drf"
version = "0.1.0"
description = "drf tutorial"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
    "djangorestframework>=3.16.1",
    "pygments>=2.19.2",
    "whitenoise>=6.11.0",
]
